services:
  - type: web
    name: totodimissioni
    env: python
    repo: https://github.com/capsal22/dimissap
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn dimissapp.wsgi:application"
    envVars:
      - key: DATABASE_URL
        value: "sqlite:///db.sqlite3"
