# Generated by Django 5.1.6 on 2025-02-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("totodimissioni", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidato",
            name="immagine",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
