# Generated by Django 5.1.6 on 2025-02-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("totodimissioni", "0002_candidato_immagine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="previsione",
            name="utente",
            field=models.CharField(max_length=255),
        ),
    ]
