# Generated by Django 5.1.6 on 2025-02-12 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("totodimissioni", "0003_alter_previsione_utente"),
    ]

    operations = [
        migrations.CreateModel(
            name="UtentiCensiti",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("utente", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="previsione",
            name="utente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="totodimissioni.utenticensiti",
            ),
        ),
    ]
